### ISSUE TITLE
TypeError: Cannot read property 'Constants' of undefined

### ISSUE THREAD

**Issue by peterlandry** [react-native-community/react-native-drawer-layout-polyfill#6]
When running tests with `jest`, `expo`, and `react-navigation`, I get the following error:

```TypeError: Cannot read property 'Constants' of undefined

      at Object.<anonymous> (node_modules/react-native/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.android.js:25:48)
      at Object.get DrawerLayoutAndroid [as DrawerLayoutAndroid] (node_modules/react-native/Libraries/react-native/react-native-implementation.js:25:34)
      at Object.<anonymous> (node_modules/react-navigation/node_modules/react-native-drawer-layout-polyfill/dist/index.android.js:1:217)
      at Object.<anonymous> (node_modules/react-navigation/src/views/Drawer/DrawerView.js:5:38)
```

This is logged as an issue in `react-navigation` (https://github.com/react-community/react-navigation/issues/3049) already but it seems like it may have to do with the polyfill?

**Comment by peterlandry** [comment]
This seems to be an issue with react-native proper: https://github.com/facebook/react-native/issues/17031

Closing here
